version: "3.7"

services:
  postgres:
    container_name: arklet_db
    image: postgres:14-alpine
    env_file:
      - ./docker/env.local
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  arklet-minter:
    container_name: arklet_minter
    restart: always
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./ark:/app/ark
      - ./ark_import:/app/ark_import
      - ./arklet:/app/arklet
    env_file:
      - ./docker/env.local
    environment:
      ARKLET_PORT: "8001"
    ports:
      - "8001:8001"

  arklet-resolver:
    container_name: arklet_resolver
    restart: always
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./ark:/app/ark
      - ./ark_import:/app/ark_import
      - ./arklet:/app/arklet
    env_file:
      - ./docker/env.local
    environment:
      ARKLET_PORT: "8000"
      RESOLVER: "true"
    ports:
      - "8000:8000"

volumes:
  postgres:
